/*
 * ClawBackup - Enhanced Backup Plugin for OpenClaw
 * Copyright 2024-2026 ClawBackup Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type {
  OpenClawPluginApi,
  OpenClawPluginDefinition,
  OpenClawPluginToolContext,
  OpenClawPluginToolFactory,
  AnyAgentTool,
} from "openclaw/plugin-sdk";
import { jsonResult } from "openclaw/plugin-sdk";
import * as os from "node:os";
import * as path from "node:path";
import {
  createBackup,
  listBackups,
  restoreBackup,
  syncBackup,
  deleteBackup,
  verifyBackup,
  getBackupStatus,
} from "./core/backup.js";

let serviceStateDir: string = "";
let defaultAgentDir: string = "";
let serviceReady = false;

function resolveStateDir(): string {
  if (serviceStateDir) {
    return serviceStateDir;
  }
  const envOverride = process.env.OPENCLAW_STATE_DIR?.trim() || process.env.CLAWDBOT_STATE_DIR?.trim();
  if (envOverride) {
    return envOverride;
  }
  return path.join(os.homedir(), ".openclaw");
}

function ensureServiceReady(): void {
  if (!serviceReady || !serviceStateDir) {
    throw new Error("ClawBackup service has not been initialized yet, please try again later");
  }
}

const ClawBackupPlugin: OpenClawPluginDefinition = {
  id: "clawbackup",
  name: "ClawBackup",
  version: "1.0.0",
  description: "Enhanced backup plugin - supports encryption, cloud storage, and cross-device recovery",

  configSchema: {
    type: "object",
    properties: {
      defaultStorage: {
        type: "string",
        default: "local",
        description: "Default storage backend",
      },
      encryption: {
        type: "object",
        properties: {
          enabled: {
            type: "boolean",
            default: false,
            description: "Enable encryption",
          },
          algorithm: {
            type: "string",
            default: "AES-256-CBC",
            description: "Encryption algorithm",
          },
        },
      },
      autoBackup: {
        type: "object",
        properties: {
          enabled: {
            type: "boolean",
            default: false,
            description: "Enable automatic backup",
          },
          schedule: {
            type: "string",
            default: "0 2 * * *",
            description: "Scheduled backup plan (cron format)",
          },
        },
      },
    },
  },

  register(api: OpenClawPluginApi): void {
    api.logger.info("ClawBackup plugin is registering...");

    api.registerService({
      id: "clawbackup",
      start: async (ctx) => {
        serviceStateDir = ctx.stateDir;
        defaultAgentDir = ctx.workspaceDir || "";
        serviceReady = true;
        api.logger.info(`ClawBackup service started, stateDir: ${serviceStateDir}`);
      },
      stop: async () => {
        serviceReady = false;
        api.logger.info("ClawBackup service stopped");
      },
    });

    const createBackupToolFactory: OpenClawPluginToolFactory = (ctx: OpenClawPluginToolContext) => ({
      name: "backup_create",
      description: "Create OpenClaw data backup. Supports encrypted storage and specified storage backend.",
      parameters: {
        type: "object",
        properties: {
          name: {
            type: "string",
            description: "Backup name (optional, auto-generated by default)",
          },
          password: {
            type: "string",
            description: "Encryption password (optional, required when encryption is enabled)",
          },
          storage: {
            type: "string",
            description: "Storage backend ID (optional, uses local storage by default)",
          },
        },
      },
      execute: async (_toolCallId: string, params: Record<string, unknown>) => {
        ensureServiceReady();
        const { name, password, storage } = params;
        try {
          const result = await createBackup(
            {
              name: name as string | undefined,
              password: password as string | undefined,
              storageBackend: storage as string | undefined,
              stateDir: serviceStateDir,
            },
            { config: ctx.config!, logger: console }
          );
          return jsonResult({
            success: true,
            backup: {
              id: result.id,
              name: result.name,
              size: result.sizeBytes,
              encrypted: result.encrypted,
              createdAt: result.createdAt,
            },
          });
        } catch (error) {
          const errorMessage = error instanceof Error ? error.message : String(error);
          return jsonResult({ success: false, error: errorMessage });
        }
      },
    });

    const listBackupsToolFactory: OpenClawPluginToolFactory = (ctx: OpenClawPluginToolContext) => ({
      name: "backup_list",
      description: "List all backups, including ClawBackup encrypted backups and OpenClaw native backups.",
      parameters: {
        type: "object",
        properties: {
          type: {
            type: "string",
            enum: ["all", "native", "clawbackup"],
            description: "Backup type filter (default: all)",
          },
          limit: {
            type: "number",
            description: "Return count limit (default: 50)",
          },
        },
      },
      execute: async (_toolCallId: string, params: Record<string, unknown>) => {
        ensureServiceReady();
        const { type = "all", limit = 50 } = params;
        try {
          const backups = await listBackups(
            { type: type as "all" | "native" | "clawbackup", limit: limit as number, stateDir: serviceStateDir },
            { config: ctx.config!, logger: console }
          );
          return jsonResult({
            success: true,
            count: backups.length,
            backups: backups.map((b) => ({
              id: b.id,
              type: b.type,
              name: b.name,
              size: b.sizeBytes,
              encrypted: b.encrypted,
              createdAt: b.createdAt,
            })),
          });
        } catch (error) {
          const errorMessage = error instanceof Error ? error.message : String(error);
          return jsonResult({ success: false, error: errorMessage });
        }
      },
    });

    const restoreBackupToolFactory: OpenClawPluginToolFactory = (ctx: OpenClawPluginToolContext) => ({
      name: "backup_restore",
      description: "Restore specified backup. Supports encrypted and native backups.",
      parameters: {
        type: "object",
        properties: {
          backup_id: {
            type: "string",
            description: "Backup ID to restore",
          },
          target: {
            type: "string",
            description: "Restore target path (optional, restores to original location by default)",
          },
          password: {
            type: "string",
            description: "Decryption password (required for encrypted backups)",
          },
        },
        required: ["backup_id"],
      },
      execute: async (_toolCallId: string, params: Record<string, unknown>) => {
        ensureServiceReady();
        const { backup_id, target, password } = params;
        const agentDir = ctx.agentDir || defaultAgentDir;
        try {
          const result = await restoreBackup(
            {
              backupId: backup_id as string,
              targetPath: target as string | undefined,
              password: password as string | undefined,
              stateDir: serviceStateDir,
              agentDir,
            },
            { config: ctx.config!, logger: console }
          );
          return jsonResult({
            success: true,
            restored: {
              backupId: result.backupId,
              targetPath: result.targetPath,
            },
          });
        } catch (error) {
          const errorMessage = error instanceof Error ? error.message : String(error);
          return jsonResult({ success: false, error: errorMessage });
        }
      },
    });

    const syncBackupToolFactory: OpenClawPluginToolFactory = (ctx: OpenClawPluginToolContext) => ({
      name: "backup_sync",
      description: "Sync local backup to remote storage (e.g., S3).",
      parameters: {
        type: "object",
        properties: {
          backup_id: {
            type: "string",
            description: "Backup ID to sync",
          },
          storage: {
            type: "string",
            description: "Target storage backend ID",
          },
          force: {
            type: "boolean",
            description: "Force overwrite existing remote backup",
          },
        },
        required: ["backup_id"],
      },
      execute: async (_toolCallId: string, params: Record<string, unknown>) => {
        ensureServiceReady();
        const { backup_id, storage, force } = params;
        try {
          const result = await syncBackup(
            {
              backupId: backup_id as string,
              storageBackend: storage as string | undefined,
              force: force as boolean | undefined,
              stateDir: serviceStateDir,
            },
            { config: ctx.config!, logger: console }
          );
          return jsonResult({
            success: result.success,
            backupId: result.backupId,
            remotePath: result.remotePath,
            error: result.error,
          });
        } catch (error) {
          const errorMessage = error instanceof Error ? error.message : String(error);
          return jsonResult({ success: false, error: errorMessage });
        }
      },
    });

    const deleteBackupToolFactory: OpenClawPluginToolFactory = (ctx: OpenClawPluginToolContext) => ({
      name: "backup_delete",
      description: "Delete specified backup.",
      parameters: {
        type: "object",
        properties: {
          backup_id: {
            type: "string",
            description: "Backup ID to delete",
          },
        },
        required: ["backup_id"],
      },
      execute: async (_toolCallId: string, params: Record<string, unknown>) => {
        ensureServiceReady();
        const { backup_id } = params;
        try {
          const result = await deleteBackup(
            { backupId: backup_id as string, stateDir: serviceStateDir },
            { config: ctx.config!, logger: console }
          );
          return jsonResult({
            success: result.success,
            backupId: result.backupId,
          });
        } catch (error) {
          const errorMessage = error instanceof Error ? error.message : String(error);
          return jsonResult({ success: false, error: errorMessage });
        }
      },
    });

    const verifyBackupToolFactory: OpenClawPluginToolFactory = (ctx: OpenClawPluginToolContext) => ({
      name: "backup_verify",
      description: "Verify backup integrity.",
      parameters: {
        type: "object",
        properties: {
          backup_id: {
            type: "string",
            description: "Backup ID to verify",
          },
        },
        required: ["backup_id"],
      },
      execute: async (_toolCallId: string, params: Record<string, unknown>) => {
        ensureServiceReady();
        const { backup_id } = params;
        try {
          const result = await verifyBackup(
            { backupId: backup_id as string, stateDir: serviceStateDir },
            { config: ctx.config!, logger: console }
          );
          return jsonResult({
            success: true,
            valid: result.valid,
            backupId: result.backupId,
            error: result.error,
          });
        } catch (error) {
          const errorMessage = error instanceof Error ? error.message : String(error);
          return jsonResult({ success: false, error: errorMessage });
        }
      },
    });

    const backupStatusToolFactory: OpenClawPluginToolFactory = (ctx: OpenClawPluginToolContext) => ({
      name: "backup_status",
      description: "Get backup status overview, including total count, size, recent backups, etc.",
      parameters: {
        type: "object",
        properties: {},
      },
      execute: async (_toolCallId: string) => {
        ensureServiceReady();
        const status = await getBackupStatus({ config: ctx.config!, logger: console, stateDir: serviceStateDir });
        return jsonResult({
          success: true,
          status: {
            totalBackups: status.totalBackups,
            totalSizeBytes: status.totalSizeBytes,
            lastBackupAt: status.lastBackupAt,
            nativeBackupsCount: status.nativeBackupsCount,
            storageBackends: status.storageBackends,
          },
        });
      },
    });

    api.registerTool(createBackupToolFactory);
    api.registerTool(listBackupsToolFactory);
    api.registerTool(restoreBackupToolFactory);
    api.registerTool(syncBackupToolFactory);
    api.registerTool(deleteBackupToolFactory);
    api.registerTool(verifyBackupToolFactory);
    api.registerTool(backupStatusToolFactory);

    api.logger.info("All tools registered");

    api.registerCli(
      (cliCtx) => {
        const { program, config, logger } = cliCtx;
        const root = program
          .command("clawbackup")
          .description("ClawBackup enhanced backup plugin")
          .addHelpText("after", () => `\nDocumentation: https://github.com/ClawBackup-AI/ClawBackup\n`);

        root
          .command("create [name]")
          .description("Create backup")
          .option("--password <password>", "Encryption password")
          .option("--storage <backend>", "Storage backend ID")
          .option("--output <path>", "Output file path")
          .option("--no-workspace", "Exclude workspace directory")
          .option("--only-config", "Backup config files only")
          .option("--workspace <path...>", "Specify workspace directories (multiple allowed)")
          .option("--dry-run", "Analyze backup content only, do not actually write file")
          .option("--json", "JSON format output")
          .action(async (name: string, options: { 
            password?: string; 
            storage?: string; 
            output?: string;
            noWorkspace?: boolean;
            onlyConfig?: boolean;
            workspace?: string[];
            dryRun?: boolean;
            json?: boolean 
          }) => {
            const { createBackupCommand } = await import("./commands/create.js");
            await createBackupCommand({ 
              name, 
              ...options,
              includeWorkspace: !options.noWorkspace,
            }, { config, logger, stateDir: resolveStateDir(), agentDir: cliCtx.workspaceDir || "" });
          });

        root
          .command("list")
          .description("List backups")
          .option("--type <type>", "Backup type filter (all|native|clawbackup)")
          .option("--limit <number>", "Limit return count", parseInt)
          .option("--json", "JSON format output")
          .action(async (options: { type?: string; limit?: number; json?: boolean }) => {
            const { listBackupsCommand } = await import("./commands/list.js");
            await listBackupsCommand(options, { config, logger, stateDir: resolveStateDir() });
          });

        root
          .command("restore <id>")
          .description("Restore backup")
          .option("--target <path>", "Restore target path")
          .option("--password <password>", "Decryption password")
          .option("--snapshot", "Create snapshot of current directory before restore")
          .option("--from-remote <backend>", "Restore from remote storage")
          .option("--json", "JSON format output")
          .action(async (id: string, options: { target?: string; password?: string; snapshot?: boolean; fromRemote?: string; json?: boolean }) => {
            const { restoreBackupCommand } = await import("./commands/restore.js");
            await restoreBackupCommand(id, options, { config, logger, stateDir: resolveStateDir() });
          });

        root
          .command("sync <id>")
          .description("Sync backup to remote")
          .option("--storage <backend>", "Target storage backend")
          .option("--force", "Force overwrite existing backup")
          .option("--json", "JSON format output")
          .action(async (id: string, options: { storage?: string; force?: boolean; json?: boolean }) => {
            const { syncBackupCommand } = await import("./commands/sync.js");
            await syncBackupCommand(id, options, { config, logger, stateDir: resolveStateDir() });
          });

        root
          .command("delete <id>")
          .description("Delete backup")
          .option("--yes", "Skip confirmation prompt")
          .option("--json", "JSON format output")
          .action(async (id: string, options: { yes?: boolean; json?: boolean }) => {
            const { deleteBackupCommand } = await import("./commands/delete.js");
            await deleteBackupCommand(id, options, { config, logger, stateDir: resolveStateDir() });
          });

        root
          .command("verify <id>")
          .description("Verify backup integrity")
          .option("--json", "JSON format output")
          .action(async (id: string, options: { json?: boolean }) => {
            const { verifyBackupCommand } = await import("./commands/verify.js");
            await verifyBackupCommand(id, options, { config, logger, stateDir: resolveStateDir() });
          });

        root
          .command("status")
          .description("Backup status overview")
          .option("--json", "JSON format output")
          .action(async (options: { json?: boolean }) => {
            const { statusCommand } = await import("./commands/status.js");
            await statusCommand(options, { config, logger, stateDir: resolveStateDir() });
          });

        const backendsCmd = root
          .command("backends")
          .description("Storage backend management")
          .action(async () => {
            const { backendsCommand } = await import("./commands/backends.js");
            await backendsCommand({ config, logger, stateDir: resolveStateDir() });
          });

        backendsCmd
          .command("add")
          .description("Add new storage backend")
          .action(async () => {
            const { backendsAddCommand } = await import("./commands/backends.js");
            await backendsAddCommand({ config, logger, stateDir: resolveStateDir() });
          });

        backendsCmd
          .command("remove <backendId>")
          .description("Remove storage backend")
          .action(async (backendId: string) => {
            const { backendsRemoveCommand } = await import("./commands/backends.js");
            await backendsRemoveCommand(backendId, { config, logger, stateDir: resolveStateDir() });
          });

        root
          .command("init")
          .description("Initialize ClawBackup configuration")
          .action(async () => {
            const { initCommand } = await import("./commands/init.js");
            await initCommand({ config, logger, stateDir: resolveStateDir() });
          });

        api.logger.info("CLI commands registered");
      },
      { commands: ["clawbackup"] }
    );

    api.logger.info("ClawBackup plugin registration completed");
  },

  activate(api: OpenClawPluginApi): void {
    api.logger.info("ClawBackup plugin activated");
  },
};

export default ClawBackupPlugin;

export function register(api: OpenClawPluginApi): void {
  ClawBackupPlugin.register?.(api);
}

export function activate(api: OpenClawPluginApi): void {
  ClawBackupPlugin.activate?.(api);
}

export { ClawBackupPlugin };
